### ISSUE TITLE
kubeflow 1.3 not creating gpu notebooks

### ISSUE THREAD

**Issue by brettkoonce** [canonical/notebook-operators#10]
I was able to get a kubeflow 1.3 installation using microk8s 1.21 and the steps documented here (with a --purge of microk8s/juju before):  https://github.com/ubuntu/microk8s/issues/2253#issuecomment-838158746

However, when creating a new notebook, I get the following error:

<img width="685" alt="Screen Shot 2021-05-11 at 11 40 03 AM" src="https://user-images.githubusercontent.com/11281814/118003094-dd14b280-b30d-11eb-8c55-060b96d90fec.png">

Vanilla config, eg:

<img width="920" alt="Screen Shot 2021-05-11 at 11 40 15 AM" src="https://user-images.githubusercontent.com/11281814/118003134-e867de00-b30d-11eb-87e1-5ae0a92e8cf1.png">

**Comment by knkski** [comment]
@brettkoonce https://github.com/canonical/bundle-kubeflow/pull/380 will propagate the fix for this to the stable charmed kubeflow bundle. We'll also need to update the script for `microk8s enable kubeflow`, though until then if you've got an existing installation, you can run `juju upgrade-charm jupyter-controller && juju upgrade-charm jupyter-ui`.
