### ISSUE TITLE
Charmed Kubeflow is missing R-studio

### ISSUE THREAD

**Issue by marowid** [canonical/notebook-operators#254]
The Upstream Kubeflow project has R-Studio image - https://www.kubeflow.org/docs/components/notebooks/container-images/
and it's missing from CKF. Can you please add it ?

**Comment by ca-scribner** [comment]
@marowid are you talking about [this image](https://github.com/canonical/notebook-operators/blob/447430001c4225dcddfee27ae1ceff6498814f39/charms/jupyter-ui/src/spawner_ui_config.yaml#L47) or other rstudio images?  This one is at least included in the notebook UI already, otherwise there's a bug blocking its display.

**Comment by ca-scribner** [comment]
And it isn't present in the ui?  I'm seeing it on my side:

![image](https://github.com/canonical/notebook-operators/assets/48125859/ba277ecb-dde0-4aeb-82d4-d06551c06d59)

**Comment by kimwnasptd** [comment]
So @ca-scribner what's the pending work here? Is an RStudio notebook indeed not accessible?

**Comment by marowid** [comment]
I was not able to see it in 1.6, but if it's there now you can close this bug.
